//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EdlinSoftware.Adviser.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EdlinSoftware.Adviser.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language with this name already exists..
        /// </summary>
        internal static string LanguageExists {
            get {
                return ResourceManager.GetString("LanguageExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adviser object can&apos;t be null..
        /// </summary>
        internal static string NoAdviserObject {
            get {
                return ResourceManager.GetString("NoAdviserObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language does not exist..
        /// </summary>
        internal static string NoLanguageExists {
            get {
                return ResourceManager.GetString("NoLanguageExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of programming language can&apos;t be null or empty..
        /// </summary>
        internal static string NoLanguageName {
            get {
                return ResourceManager.GetString("NoLanguageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platform does not exist..
        /// </summary>
        internal static string NoPlatformExists {
            get {
                return ResourceManager.GetString("NoPlatformExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of design platform can&apos;t be null or empty..
        /// </summary>
        internal static string NoPlatformName {
            get {
                return ResourceManager.GetString("NoPlatformName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topic does not exist..
        /// </summary>
        internal static string NoTopicExists {
            get {
                return ResourceManager.GetString("NoTopicExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platform with this name already exists..
        /// </summary>
        internal static string PlatformExists {
            get {
                return ResourceManager.GetString("PlatformExists", resourceCulture);
            }
        }
    }
}
